// The built-in strength exercise catalog: [English name (its slug is the id), Russian name, group, kind?]. Every
// exercise from the histories we import (Hevy, GymKeeper, «Дневник тренировок») is here; renames, merges and the
// other names they go by live in catalog.js.
export const SEED_EX = [
  ["Squat", "Приседания со штангой", "ноги"],
  ["Belt squat", "Присед с поясом", "ноги"],
  ["Hack squat", "Гакк-присед", "ноги"],
  ["Bulgarian split squat", "Болгарские выпады", "ноги"],
  ["Leg extension", "Разгибание ног в тренажёре", "ноги"],
  ["Leg curl", "Сгибание ног в тренажёре", "ноги"],
  ["Hip thrust", "Ягодичный мост со штангой", "ноги"],
  ["Lateral raise", "Махи гантелями в стороны", "плечи"],
  ["Overhead press", "Жим штанги стоя", "плечи"],
  ["Upright row", "Тяга штанги к подбородку", "плечи"],
  ["Reverse fly", "Обратные разведения в наклоне", "плечи"],
  ["Barbell bench press", "Жим штанги лёжа", "грудь"],
  ["Incline barbell bench press", "Жим штанги на наклонной скамье", "грудь"],
  ["Dumbbell bench press", "Жим гантелей лёжа", "грудь"],
  ["Dips", "Брусья на грудь", "грудь"],
  ["Cable crossover", "Сведение рук в кроссовере", "грудь"],
  ["Machine pec fly", "Бабочка (сведение рук в тренажёре)", "грудь"],
  ["Lat pulldown", "Тяга верхнего блока", "спина"],
  ["Pull up", "Подтягивания средним хватом", "спина"],
  ["Bent-over barbell row", "Тяга штанги в наклоне", "спина"],
  ["Seated row", "Тяга нижнего блока сидя", "спина"],
  ["Machine row", "Тяга в рычажном тренажёре", "спина"],
  ["Pullover", "Пуловер", "спина"],
  ["Cable pullover", "Пуловер в кроссовере стоя (прямыми руками)", "спина"],
  ["Rope cable pullover", "Пуловер на блоке с канатом", "спина"],
  ["Lying cable pullover", "Пуловер лёжа на нижнем блоке", "спина"],
  ["Barbell pullover", "Пуловер со штангой", "спина"],
  ["Decline barbell pullover", "Пуловер со штангой на скамье с наклоном вниз", "спина"],
  ["EZ-bar pullover", "Пуловер с EZ-грифом", "спина"],
  ["Bent-arm dumbbell pullover", "Пуловер с гантелью согнутыми руками", "спина"],
  ["Machine pullover", "Пуловер в тренажёре", "спина"],
  ["One-arm cable pullover", "Пуловер одной рукой в кроссовере", "спина"],
  ["Cable preacher curl", "Сгибания на Скотте в блоке", "бицепс"],
  ["Dumbbell seated curl", "Сгибания с гантелями сидя", "бицепс"],
  ["Machine preacher curl", "Сгибания на Скотте в тренажёре", "бицепс"],
  ["Cable extension", "Разгибания рук на блоке", "трицепс"],
  ["Cable extension samurai", "Разгибания на блоке из-за головы (самурай)", "трицепс"],
  ["Triceps kickback", "Разгибание назад в наклоне (лыжник)", "трицепс"],
  ["Triceps press machine", "Жим на трицепс в тренажёре", "трицепс"],
  ["Wrist curl", "Сгибания запястий", "предплечья"],
  ["Calf raise", "Подъёмы на носки", "икры"],
  ["Deadlift", "Становая тяга", "кор"],
  ["Farmer's walk", "Прогулка фермера", "кор", "time"],
  // from GymKeeper list
  ["Duck press", "Жим «уточка»", "плечи"],
  ["Reverse pec deck", "Обратные разведения в тренажёре на заднюю дельту (пекдек)", "плечи"],
  ["Plate overhead press", "Жим блина над головой", "плечи"],
  ["Dumbbell shoulder press", "Жим гантелей над головой стоя", "плечи"],
  ["Cable shoulder press", "Жим над головой в нижнем блоке", "плечи"],
  ["Machine shoulder press", "Жим над головой в тренажёре", "плечи"],
  ["Lying rear delt raise", "Махи лёжа на заднюю дельту", "плечи"],
  ["Rear delt row", "Тяга на задние дельты", "плечи"],
  ["Kettlebell lift", "Подъём гири", "ноги"],
  ["Side leg raise", "Боковые махи ногой", "ноги"],
  ["Horizontal leg press", "Жим ногами горизонтальный", "ноги"],
  ["Cable hip abduction", "Отведение ноги в кроссовере", "ноги"],
  ["Bodyweight squat", "Приседания без веса", "ноги"],
  ["Dumbbell squat", "Приседания с гантелями", "ноги"],
  ["Smith machine squat", "Приседания в Смите", "ноги"],
  ["Barbell hack squat", "Гакк-приседания со штангой", "ноги"],
  ["Cable back row", "Тяга в кроссовере на спину", "спина"],
  ["Assisted pull-up", "Подтягивания в гравитроне", "спина"],
  ["Inverted row", "Подтягивания на нижней перекладине", "спина"],
  ["Dumbbell bent-over row", "Тяга гантелей в наклоне", "спина"],
  ["Close-grip dumbbell press", "Жим гантелей узким хватом", "грудь"],
  ["Svend press", "Жим Свенда", "грудь"],
  ["Cable bench press", "Жим лёжа в нижнем блоке", "грудь"],
  ["Smith machine bench press", "Жим лёжа в Смите", "грудь"],
  ["Incline dumbbell press", "Жим гантелей на наклонной", "грудь"],
  ["Incline cable press", "Жим на наклонной в нижнем блоке", "грудь"],
  ["Incline Smith press", "Жим на наклонной в Смите", "грудь"],
  ["One-arm cable shoulder press", "Жим над головой одной рукой в блоке", "плечи"],
  ["One-arm machine shoulder press", "Жим над головой одной рукой в тренажёре", "плечи"],
  ["One-arm reverse pec deck", "Обратные разведения в тренажёре одной рукой (пекдек)", "плечи"],
  ["One-arm rear delt row", "Тяга на заднюю дельту одной рукой", "плечи"],
  ["Single-leg leg press", "Жим одной ногой", "ноги"],
  ["One-arm cable row", "Тяга одной рукой в кроссовере", "спина"],
  ["One-arm cable chest press", "Жим одной рукой в нижнем блоке", "грудь"],
  ["One-arm incline dumbbell press", "Жим гантели одной рукой на наклонной", "грудь"],
  ["One-arm incline cable press", "Жим одной рукой на наклонной в блоке", "грудь"],
  // from GymKeeper (second phone)
  ["Sumo deadlift", "Становая тяга сумо", "ноги"],
  ["Romanian deadlift", "Румынская тяга со штангой", "ноги"],
  ["Lying leg curl", "Сгибание ног лёжа в тренажёре", "ноги"],
  ["Machine chest press", "Жим от груди сидя в тренажёре", "грудь"],
  ["Push-up", "Отжимания", "грудь"],
  ["Close-grip chin-up", "Подтягивания обратным узким хватом", "спина"],
  ["Barbell curl", "Сгибание рук со штангой", "бицепс"],
  ["Triceps dips", "Брусья на трицепс", "трицепс"],
  ["Single-leg lying leg curl", "Сгибание одной ноги лёжа", "ноги"],
  ["One-arm machine chest press", "Жим от груди одной рукой в тренажёре", "грудь"],
  ["One-arm push-up", "Отжимания на одной руке", "грудь"],
  // unilateral variations
  ["Single-leg leg extension", "Разгибание одной ноги в тренажёре", "ноги"],
  ["Single-leg leg curl", "Сгибание одной ноги в тренажёре", "ноги"],
  ["Single-leg hip thrust", "Ягодичный мост на одной ноге", "ноги"],
  ["Single-leg Romanian deadlift", "Румынская тяга на одной ноге", "ноги"],
  ["Single-leg calf raise", "Подъёмы на носок одной ногой", "икры"],
  ["One-arm lateral raise", "Махи одной рукой в сторону", "плечи"],
  ["One-arm shoulder press", "Жим гантели одной рукой стоя", "плечи"],
  ["One-arm upright row", "Тяга к подбородку одной рукой", "плечи"],
  ["One-arm reverse fly", "Обратные разведения одной рукой", "плечи"],
  ["One-arm dumbbell bench press", "Жим гантели одной рукой лёжа", "грудь"],
  ["Single-arm cable crossover", "Сведение одной рукой в кроссовере", "грудь"],
  ["One-arm machine pec fly", "Бабочка одной рукой", "грудь"],
  ["One-arm lat pulldown", "Тяга верхнего блока одной рукой", "спина"],
  ["One-arm seated row", "Тяга нижнего блока одной рукой", "спина"],
  ["One-arm machine row", "Тяга в рычажном тренажёре одной рукой", "спина"],
  ["One-arm dumbbell row", "Тяга гантели одной рукой в наклоне", "спина"],
  ["One-arm cable preacher curl", "Сгибание на Скотте одной рукой в блоке", "бицепс"],
  ["One-arm machine preacher curl", "Сгибание на Скотте одной рукой в тренажёре", "бицепс"],
  ["One-arm seated dumbbell curl", "Сгибание гантели одной рукой сидя", "бицепс"],
  ["One-arm cable extension", "Разгибание одной рукой на блоке", "трицепс"],
  ["One-arm cable extension samurai", "Разгибание одной рукой на блоке из-за головы", "трицепс"],
  ["One-arm triceps kickback", "Разгибание назад одной рукой (лыжник)", "трицепс"],
  ["One-arm triceps press machine", "Жим на трицепс одной рукой в тренажёре", "трицепс"],
  ["One-arm wrist curl", "Сгибание запястья одной рукой", "предплечья"],
  ["Suitcase carry", "Прогулка фермера одной рукой", "кор", "time"],
  // from the history imported from Hevy / GymKeeper (with the one-sided variations that were done)
  ["Front squat", "Фронтальные приседания со штангой", "ноги"],
  ["Dumbbell front squat", "Фронтальные приседания с гантелями", "ноги"],
  ["Leg press", "Жим ногами под углом (45°)", "ноги"],
  ["Dumbbell lunge", "Выпады с гантелями", "ноги"],
  ["Barbell lunge", "Выпады со штангой", "ноги"],
  ["Single-leg squat", "Приседания на одной ноге (пистолет)", "ноги"],
  ["Close-grip bench press", "Жим штанги узким хватом", "трицепс"],
  ["Incline dumbbell fly", "Разводка гантелей на наклонной", "грудь"],
  ["Hammer Strength press", "Жим в рычажном тренажёре Hammer", "грудь"],
  ["One-arm Hammer Strength press", "Жим одной рукой в рычажном тренажёре Hammer", "грудь"],
  ["Decline push-up", "Отжимания с ногами на возвышении", "грудь"],
  ["T-bar row", "Тяга Т-грифа в наклоне", "спина"],
  ["Incline dumbbell row", "Тяга гантелей лёжа на наклонной", "спина"],
  ["Close-grip lat pulldown", "Тяга верхнего блока узким хватом", "спина"],
  ["Machine lat pulldown", "Тяга сверху в рычажном тренажёре", "спина"],
  ["One-arm machine lat pulldown", "Тяга сверху одной рукой в рычажном тренажёре", "спина"],
  ["Wide-grip pull-up", "Подтягивания широким хватом", "спина"],
  ["Close-grip pull-up", "Подтягивания узким хватом", "спина"],
  ["Hyperextension", "Гиперэкстензия", "спина"],
  ["Barbell shrug", "Шраги со штангой", "спина"],
  ["Dumbbell shrug", "Шраги с гантелями", "спина"],
  ["Seated barbell press", "Жим штанги сидя", "плечи"],
  ["Seated dumbbell press", "Жим гантелей над головой сидя", "плечи"],
  ["Cable lateral raise", "Махи в сторону на нижнем блоке", "плечи"],
  ["One-arm cable lateral raise", "Мах одной рукой в сторону на нижнем блоке", "плечи"],
  ["Dumbbell front raise", "Подъёмы гантелей перед собой", "плечи"],
  ["Cable front raise", "Подъёмы перед собой на нижнем блоке", "плечи"],
  ["One-arm cable front raise", "Подъём одной рукой перед собой на блоке", "плечи"],
  ["Cable reverse fly", "Обратные разведения на блоке", "плечи"],
  ["Dumbbell upright row", "Тяга гантелей к подбородку", "плечи"],
  ["Machine upright row", "Тяга к подбородку в тренажёре", "плечи"],
  ["Dumbbell curl", "Сгибания с гантелями стоя", "бицепс"],
  ["One-arm dumbbell curl", "Сгибание гантели одной рукой стоя", "бицепс"],
  ["Incline dumbbell curl", "Сгибания с гантелями на наклонной скамье", "бицепс"],
  ["Barbell preacher curl", "Сгибания на Скотте со штангой", "бицепс"],
  ["Cable curl", "Сгибания на нижнем блоке", "бицепс"],
  ["One-arm cable curl", "Сгибание одной рукой на нижнем блоке", "бицепс"],
  ["Machine curl", "Сгибания рук в тренажёре", "бицепс"],
  ["Seated overhead barbell extension", "Французский жим сидя со штангой", "трицепс"],
  ["Bench dips", "Обратные отжимания от скамьи", "трицепс"],
  ["Crunch", "Скручивания", "кор"],
  ["Cable crunch", "Скручивания на блоке", "кор"],
  ["Machine crunch", "Скручивания в тренажёре", "кор"],
  ["Hanging knee raise", "Подъём коленей в висе", "кор"],
  ["Lying leg raise", "Подъём ног лёжа", "кор"],
  ["Bird dog", "Птица-собака", "кор"],
  ["Burpee", "Бёрпи", "кор"],
  // cardio: a "set" is a stretch of minutes, with an optional distance
  ["Treadmill run", "Бег на дорожке", "кардио", "cardio"],
  ["Running", "Бег на улице", "кардио", "cardio"],
  ["Treadmill walk", "Ходьба на дорожке", "кардио", "cardio"],
  ["Elliptical", "Эллипс", "кардио", "cardio"],
  ["Rowing machine", "Гребной тренажёр", "кардио", "cardio"],
  ["Exercise bike", "Велотренажёр", "кардио", "cardio"],
  ["Stair climber", "Степпер-лестница", "кардио", "cardio"],
  ["Jump rope", "Скакалка", "кардио", "cardio"],
  // from «Дневник тренировок»
  ["Decline barbell bench press", "Жим штанги лёжа головой вниз", "грудь"],
  ["Barbell rear delt row", "Тяга штанги в наклоне на задние дельты", "плечи"],
  ["Machine lateral raise", "Махи в стороны в тренажёре", "плечи"],
  ["Seated calf raise", "Подъёмы на носки сидя в тренажёре", "икры"],
  ["Smith machine shoulder press", "Жим над головой в Смите", "плечи"],
  ["Standing cable leg curl", "Сгибание ноги стоя в кроссовере", "ноги"],
  ["Dumbbell fly", "Разводка гантелей лёжа", "грудь"],
  // from GymKeeper's Russian export
  ["Face pull", "Тяга к лицу на задние дельты (верхний блок)", "плечи"],
  ["Machine hip abduction", "Разведение ног сидя в тренажёре", "ноги"],
  ["Machine hip adduction", "Сведение ног сидя в тренажёре", "ноги"],
  ["Dumbbell Romanian deadlift", "Румынская тяга с гантелями", "ноги"],
  ["Dumbbell sumo squat", "Приседания сумо с гантелью", "ноги"],
  ["Seated dumbbell overhead extension", "Французский жим гантели сидя", "трицепс"],
  ["Hammer curl", "Сгибания молотковым хватом с гантелями (молотки)", "бицепс"],
  ["Cable hammer curl", "Молотки на нижнем блоке с канатом", "бицепс"],
  ["Reverse dumbbell curl", "Сгибания с гантелями обратным хватом", "предплечья"],
  ["One-arm dumbbell preacher curl", "Сгибание гантели одной рукой на Скотте", "бицепс"],
  ["Machine glute kickback", "Махи ногой назад в тренажёре", "ноги"],
  ["Cable glute kickback", "Махи ногой назад в нижнем блоке", "ноги"],
  ["Chin-up", "Подтягивания обратным хватом", "спина"],
  ["Reverse-grip lat pulldown", "Тяга верхнего блока обратным хватом", "спина"],
  ["Behind-the-neck lat pulldown", "Тяга верхнего блока за голову", "спина"],
  ["Bent-over cable row", "Тяга нижнего блока в наклоне", "спина"],
  ["Standing cable chest press", "Жим от груди стоя в кроссовере", "грудь"],
  ["Arnold press", "Жим Арнольда", "плечи"],
  ["Plate front raise", "Подъём блина перед собой", "плечи"],
  ["Dumbbell skull crusher", "Французский жим лёжа с гантелями", "трицепс"],
  ["Skull crusher", "Французский жим лёжа со штангой", "трицепс"],
  ["One-arm cable kickback", "Разгибание руки назад в наклоне на нижнем блоке", "трицепс"],
  ["Step-up", "Зашагивания на платформу", "ноги"],
  ["Dumbbell step-up", "Зашагивания на платформу с гантелями", "ноги"],
  ["Dumbbell split squat", "Сплит-приседания с гантелями", "ноги"],
  ["Dumbbell deadlift", "Становая тяга с гантелями", "кор"],
  ["Smith machine deadlift", "Становая тяга в Смите", "кор"],
  ["Smith machine sumo deadlift", "Становая тяга сумо в Смите", "ноги"],
  ["Dumbbell hip thrust", "Ягодичный мост с гантелью", "ноги"],
  ["Dumbbell lying leg curl", "Сгибание ног лёжа с гантелью", "ноги"],
  ["Good morning", "Наклоны со штангой на плечах (гуд морнинг)", "ноги"],
  ["Wall sit", "Стульчик у стены", "ноги", "time"],
  ["Sled push", "Толкание саней", "ноги"],
  ["Leg press calf raise", "Жим носками в тренажёре", "икры"],
  ["Dumbbell calf raise", "Подъёмы на носки с гантелями", "икры"],
  ["Smith machine shrug", "Шраги в Смите", "спина"],
  ["Superman", "Супермен", "спина"],
  ["Plank", "Планка", "кор", "time"],
  ["Reverse crunch", "Обратные скручивания", "кор"],
  ["Cross crunch", "Перекрёстные скручивания", "кор"],
  ["V-up", "Складной нож", "кор"],
  ["Hanging leg raise", "Подъём ног в висе", "кор"],
  ["Captain's chair leg raise", "Подъём ног в упоре на локтях", "кор"],
  ["Cable woodchop", "Повороты корпуса на блоке", "кор"],
  ["Mountain climber", "Скалолаз", "кор"],
];
