// Names other apps use for exercises we have, mapped to our ids. Only true equivalents with the same
// equipment: merging a dumbbell variant into a barbell one would mix weights that can't be compared
// (last time's hints, records). Anything not listed is matched by name or created as a new exercise.
export const ALIASES = [
  // Hevy, Russian
  ["Присед (Штанга)", "squat"],
  ["Гакк-приседания (Тренажёр)", "hack-squat"],
  ["Разгибание ног (Тренажёр)", "leg-extension"],
  ["Сгибание ног лёжа (Тренажёр)", "lying-leg-curl"],
  ["Сгибание ног сидя (Тренажёр)", "leg-curl"],
  ["Боковые подъемы (Гантель)", "lateral-raise"],
  ["Махи в стороны (Гантели)", "lateral-raise"],
  ["Тяга в наклоне (Штанга)", "bent-over-barbell-row"],
  ["Горизонтальная тяга блока", "seated-row"],
  ["Жим в наклоне лежа (Гантель)", "incline-dumbbell-press"],
  ["Жим лёжа на наклонной скамье (Гантели)", "incline-dumbbell-press"],
  ["Жим в наклоне лежа (Штанга)", "incline-barbell-bench-press"],
  ["Жим лёжа (Штанга)", "barbell-bench-press"],
  ["Жим лёжа (Гантель)", "dumbbell-bench-press"],
  ["Пуловер (Гантель)", "pullover"],
  ["Сгибание рук на скамье Скотта (Тренажёр)", "machine-preacher-curl"],
  ["Разгибание рук на трицепс с канатом (блок)", "cable-extension"],
  ["Вертикальная тяга Широчайшими (Блок)", "lat-pulldown"],
  ["Тяга к подбородку (Штанга)", "upright-row"],
  ["Разводка (Тренажёр)", "machine-pec-fly"],
  ["Становая тяга (Штанга)", "deadlift"],
  ["Румынская становая тяга (Штанга)", "romanian-deadlift"],
  ["Подтягивания", "pull-up"],
  ["Отжимания", "push-up"],
  // Hevy, English
  ["Squat (Barbell)", "squat"],
  ["Hack Squat (Machine)", "hack-squat"],
  ["Leg Extension (Machine)", "leg-extension"],
  ["Lying Leg Curl (Machine)", "lying-leg-curl"],
  ["Seated Leg Curl (Machine)", "leg-curl"],
  ["Lateral Raise (Dumbbell)", "lateral-raise"],
  ["Bent Over Row (Barbell)", "bent-over-barbell-row"],
  ["Seated Cable Row - V Grip (Cable)", "seated-row"],
  ["Incline Bench Press (Dumbbell)", "incline-dumbbell-press"],
  ["Incline Bench Press (Barbell)", "incline-barbell-bench-press"],
  ["Bench Press (Barbell)", "barbell-bench-press"],
  ["Bench Press (Dumbbell)", "dumbbell-bench-press"],
  ["Pullover (Dumbbell)", "pullover"],
  ["Preacher Curl (Machine)", "machine-preacher-curl"],
  ["Triceps Rope Pushdown", "cable-extension"],
  ["Triceps Pushdown", "cable-extension"],
  ["Lat Pulldown (Cable)", "lat-pulldown"],
  ["Upright Row (Barbell)", "upright-row"],
  ["Chest Fly (Machine)", "machine-pec-fly"],
  ["Butterfly (Pec Deck)", "machine-pec-fly"],
  ["Deadlift (Barbell)", "deadlift"],
  ["Romanian Deadlift (Barbell)", "romanian-deadlift"],
  ["Overhead Press (Barbell)", "overhead-press"],
  ["Shoulder Press (Dumbbell)", "dumbbell-shoulder-press"],
  ["Hip Thrust (Barbell)", "hip-thrust"],
  ["Bulgarian Split Squat", "bulgarian-split-squat"],
  ["Bicep Curl (Barbell)", "barbell-curl"],
  ["Pull Up", "pull-up"],
  ["Push Up", "push-up"],
  ["Chest Dip", "dips"],
  ["Standing Calf Raise (Machine)", "calf-raise"],
  // GymKeeper ("Squat · Barbell" is read as "Squat (Barbell)")
  ["Squat (Barbell)", "squat"],
  ["Overhead Press (Dumbbell)", "dumbbell-shoulder-press"],
  ["Overhead Press (Machine)", "machine-shoulder-press"],
  ["Lateral Raise (Dumbbell)", "lateral-raise"],
  ["Incline Bench Press (Dumbbell)", "incline-dumbbell-press"],
  ["Incline Bench Press (Smith Machine)", "incline-smith-press"],
  ["Bench Press (Smith Machine)", "smith-machine-bench-press"],
  ["Bench Press (Cable)", "cable-bench-press"],
  ["Tricep Extension (Cable)", "cable-extension"],
  ["Overhead Tricep Extension (Cable)", "cable-extension-samurai"],
  ["Tricep Kickback (Dumbbell)", "triceps-kickback"],
  ["Curl (Barbell)", "barbell-curl"],
  ["Seated Row (Cable)", "seated-row"],
  ["Seated Row (Machine)", "machine-row"],
  ["Rear Delt Row (Cable)", "rear-delt-row"],
  ["Lat Pull Down (Cable)", "lat-pulldown"],
  ["Straight Arm Lat Pull Down (Cable)", "cable-pullover"],
  ["Pullover (Barbell)", "barbell-pullover"],
  ["Single Arm Bent Over Row (Dumbbell)", "one-arm-dumbbell-row"],
  ["Bent Over Row (Dumbbell)", "dumbbell-bent-over-row"],
  ["Bent Over Reverse Fly (Dumbbell)", "reverse-fly"],
  ["Squat (Smith Machine)", "smith-machine-squat"],
  ["Pec Deck (Machine)", "machine-pec-fly"],
  ["Leg Curl (Machine)", "leg-curl"],
  ["Lying Leg Curl (Machine)", "lying-leg-curl"],
  ["Hip Thrust", "hip-thrust"],
  ["Chin Up", "close-grip-chin-up"],
  ["Inverted Row", "inverted-row"],
  ["Standing Calf Raise", "calf-raise"],
  ["Standing Chest Fly (Cable)", "cable-crossover"],
  ["Bench Press (Close Grip) (Barbell)", "close-grip-bench-press"],
  ["Bent Over Row (T-Bar)", "t-bar-row"],
  ["Crunch", "crunch"],
  ["Crunch (Cable)", "cable-crunch"],
  ["Crunch (Machine)", "machine-crunch"],
  ["Curl (Cable)", "cable-curl"],
  ["Curl (Dumbbell)", "dumbbell-curl"],
  ["Curl (Machine)", "machine-curl"],
  ["Decline Push Up", "decline-push-up"],
  ["Front Raise (Cable)", "cable-front-raise"],
  ["Front Raise (Dumbbell)", "dumbbell-front-raise"],
  ["Front Squat (Barbell)", "front-squat"],
  ["Front Squat (Dumbbell)", "dumbbell-front-squat"],
  ["Hammer Strength Press (Machine)", "hammer-strength-press"],
  ["Hanging Knee Raise", "hanging-knee-raise"],
  ["Hyperextension", "hyperextension"],
  ["Incline Chest Fly (Dumbbell)", "incline-dumbbell-fly"],
  ["Incline Curl (Dumbbell)", "incline-dumbbell-curl"],
  ["Incline Row (Dumbbell)", "incline-dumbbell-row"],
  ["Lat Pull Down (Close Grip) (Cable)", "close-grip-lat-pulldown"],
  ["Lat Pull Down (Machine)", "machine-lat-pulldown"],
  ["Lateral Raise (Cable)", "cable-lateral-raise"],
  ["Leg Press (Machine)", "leg-press"],
  ["Lunge (Barbell)", "barbell-lunge"],
  ["Lunge (Dumbbell)", "dumbbell-lunge"],
  ["Lying Leg Raise", "lying-leg-raise"],
  ["Preacher Curl (Barbell)", "barbell-preacher-curl"],
  ["Pull Up (Wide Grip)", "wide-grip-pull-up"],
  ["Reverse Fly (Cable)", "cable-reverse-fly"],
  ["Seated Overhead Press (Barbell)", "seated-barbell-press"],
  ["Seated Overhead Press (Dumbbell)", "seated-dumbbell-press"],
  ["Seated Overhead Tricep Extension (Barbell)", "seated-overhead-barbell-extension"],
  ["Shrug (Barbell)", "barbell-shrug"],
  ["Shrug (Dumbbell)", "dumbbell-shrug"],
  ["Single Leg Deadlift (Dumbbell)", "single-leg-romanian-deadlift"],
  ["Single Leg Squat", "single-leg-squat"],
  ["Tricep Dip (Bench)", "bench-dips"],
  ["Upright Row (Dumbbell)", "dumbbell-upright-row"],
  ["Bird Dog", "bird-dog"],
  ["Burpee", "burpee"],
  // GymKeeper sets noted «1рук» / «1h» / «single» / «1 нога» come as "<name> одной рукой / ногой"
  ["Seated Row (Cable) одной рукой", "one-arm-seated-row"],
  ["Incline Bench Press (Dumbbell) одной рукой", "one-arm-incline-dumbbell-press"],
  ["Standing Chest Fly (Cable) одной рукой", "single-arm-cable-crossover"],
  ["Pullover (Barbell) одной рукой", "one-arm-cable-pullover"], // noted «cbl1h»: one-arm cable pullover
  ["Hammer Strength Press (Machine) одной рукой", "one-arm-hammer-strength-press"],
  ["Lat Pull Down (Machine) одной рукой", "one-arm-machine-lat-pulldown"],
  ["Lateral Raise (Cable) одной рукой", "one-arm-cable-lateral-raise"],
  ["Leg Press (Machine) одной ногой", "single-leg-leg-press"],
  // Hevy, Russian
  ["Жим ногами (Тренажёр)", "leg-press"],
  ["Жим сидя над головой (Штанга)", "seated-barbell-press"],
  ["Наклонные сгибания на бицепс сидя (Гантель)", "incline-dumbbell-curl"],
  ["Вертикальная тяга Широчайшими (Тренажёр)", "machine-lat-pulldown"],
  ["Тяга к подбородку (Гантели)", "dumbbell-upright-row"],
  ["Вертикальная тяга (Гантель)", "dumbbell-upright-row"],
  ["Вертикальная тяга (Тренажёр)", "machine-upright-row"],
];
