// Names other apps use for exercises we have, mapped to our ids. Only true equivalents with the same
// equipment: merging a dumbbell variant into a barbell one would mix weights that can't be compared
// (last time's hints, records). Anything not listed is matched by name or created as a new exercise.
export const ALIASES = [
  // Hevy, Russian
  ["Присед (Штанга)", "squat"],
  ["Гакк-приседания (Тренажёр)", "hack-squat"],
  ["Разгибание ног (Тренажёр)", "leg-extension"],
  ["Сгибание ног лёжа (Тренажёр)", "lying-leg-curl"],
  ["Сгибание ног сидя (Тренажёр)", "leg-curl"],
  ["Боковые подъемы (Гантель)", "lateral-raise"],
  ["Махи в стороны (Гантели)", "lateral-raise"],
  ["Тяга в наклоне (Штанга)", "bent-over-barbell-row"],
  ["Горизонтальная тяга блока", "seated-row"],
  ["Жим в наклоне лежа (Гантель)", "incline-dumbbell-press"],
  ["Жим лёжа на наклонной скамье (Гантели)", "incline-dumbbell-press"],
  ["Жим в наклоне лежа (Штанга)", "incline-barbell-bench-press"],
  ["Жим лёжа (Штанга)", "barbell-bench-press"],
  ["Жим лёжа (Гантель)", "dumbbell-bench-press"],
  ["Пуловер (Гантель)", "pullover"],
  ["Сгибание рук на скамье Скотта (Тренажёр)", "machine-preacher-curl"],
  ["Разгибание рук на трицепс с канатом (блок)", "cable-extension"],
  ["Вертикальная тяга Широчайшими (Блок)", "lat-pulldown"],
  ["Тяга к подбородку (Штанга)", "upright-row"],
  ["Разводка (Тренажёр)", "machine-pec-fly"],
  ["Становая тяга (Штанга)", "deadlift"],
  ["Румынская становая тяга (Штанга)", "romanian-deadlift"],
  ["Подтягивания", "pull-up"],
  ["Отжимания", "push-up"],
  // Hevy, English
  ["Squat (Barbell)", "squat"],
  ["Hack Squat (Machine)", "hack-squat"],
  ["Leg Extension (Machine)", "leg-extension"],
  ["Lying Leg Curl (Machine)", "lying-leg-curl"],
  ["Seated Leg Curl (Machine)", "leg-curl"],
  ["Lateral Raise (Dumbbell)", "lateral-raise"],
  ["Bent Over Row (Barbell)", "bent-over-barbell-row"],
  ["Seated Cable Row - V Grip (Cable)", "seated-row"],
  ["Incline Bench Press (Dumbbell)", "incline-dumbbell-press"],
  ["Incline Bench Press (Barbell)", "incline-barbell-bench-press"],
  ["Bench Press (Barbell)", "barbell-bench-press"],
  ["Bench Press (Dumbbell)", "dumbbell-bench-press"],
  ["Pullover (Dumbbell)", "pullover"],
  ["Preacher Curl (Machine)", "machine-preacher-curl"],
  ["Triceps Rope Pushdown", "cable-extension"],
  ["Triceps Pushdown", "cable-extension"],
  ["Lat Pulldown (Cable)", "lat-pulldown"],
  ["Upright Row (Barbell)", "upright-row"],
  ["Chest Fly (Machine)", "machine-pec-fly"],
  ["Butterfly (Pec Deck)", "machine-pec-fly"],
  ["Deadlift (Barbell)", "deadlift"],
  ["Romanian Deadlift (Barbell)", "romanian-deadlift"],
  ["Overhead Press (Barbell)", "overhead-press"],
  ["Shoulder Press (Dumbbell)", "dumbbell-shoulder-press"],
  ["Hip Thrust (Barbell)", "hip-thrust"],
  ["Bulgarian Split Squat", "bulgarian-split-squat"],
  ["Bicep Curl (Barbell)", "barbell-curl"],
  ["Pull Up", "pull-up"],
  ["Push Up", "push-up"],
  ["Chest Dip", "dips"],
  ["Standing Calf Raise (Machine)", "calf-raise"],
  // GymKeeper ("Squat · Barbell" is read as "Squat (Barbell)")
  ["Squat (Barbell)", "squat"],
  ["Overhead Press (Dumbbell)", "dumbbell-shoulder-press"],
  ["Overhead Press (Machine)", "machine-shoulder-press"],
  ["Lateral Raise (Dumbbell)", "lateral-raise"],
  ["Incline Bench Press (Dumbbell)", "incline-dumbbell-press"],
  ["Incline Bench Press (Smith Machine)", "incline-smith-press"],
  ["Bench Press (Smith Machine)", "smith-machine-bench-press"],
  ["Bench Press (Cable)", "cable-bench-press"],
  ["Tricep Extension (Cable)", "cable-extension"],
  ["Overhead Tricep Extension (Cable)", "cable-extension-samurai"],
  ["Tricep Kickback (Dumbbell)", "triceps-kickback"],
  ["Curl (Barbell)", "barbell-curl"],
  ["Seated Row (Cable)", "seated-row"],
  ["Seated Row (Machine)", "machine-row"],
  ["Rear Delt Row (Cable)", "rear-delt-row"],
  ["Lat Pull Down (Cable)", "lat-pulldown"],
  ["Straight Arm Lat Pull Down (Cable)", "cable-pullover"],
  ["Pullover (Barbell)", "barbell-pullover"],
  ["Single Arm Bent Over Row (Dumbbell)", "one-arm-dumbbell-row"],
  ["Bent Over Row (Dumbbell)", "dumbbell-bent-over-row"],
  ["Bent Over Reverse Fly (Dumbbell)", "reverse-fly"],
  ["Squat (Smith Machine)", "smith-machine-squat"],
  ["Pec Deck (Machine)", "machine-pec-fly"],
  ["Leg Curl (Machine)", "leg-curl"],
  ["Lying Leg Curl (Machine)", "lying-leg-curl"],
  ["Hip Thrust", "hip-thrust"],
  ["Chin Up", "close-grip-chin-up"],
  ["Inverted Row", "inverted-row"],
  ["Standing Calf Raise", "calf-raise"],
  ["Standing Chest Fly (Cable)", "cable-crossover"],
  ["Bench Press (Close Grip) (Barbell)", "close-grip-bench-press"],
  ["Bent Over Row (T-Bar)", "t-bar-row"],
  ["Crunch", "crunch"],
  ["Crunch (Cable)", "cable-crunch"],
  ["Crunch (Machine)", "machine-crunch"],
  ["Curl (Cable)", "cable-curl"],
  ["Curl (Dumbbell)", "dumbbell-curl"],
  ["Curl (Machine)", "machine-curl"],
  ["Decline Push Up", "decline-push-up"],
  ["Front Raise (Cable)", "cable-front-raise"],
  ["Front Raise (Dumbbell)", "dumbbell-front-raise"],
  ["Front Squat (Barbell)", "front-squat"],
  ["Front Squat (Dumbbell)", "dumbbell-front-squat"],
  ["Hammer Strength Press (Machine)", "hammer-strength-press"],
  ["Hanging Knee Raise", "hanging-knee-raise"],
  ["Hyperextension", "hyperextension"],
  ["Incline Chest Fly (Dumbbell)", "incline-dumbbell-fly"],
  ["Incline Curl (Dumbbell)", "incline-dumbbell-curl"],
  ["Incline Row (Dumbbell)", "incline-dumbbell-row"],
  ["Lat Pull Down (Close Grip) (Cable)", "close-grip-lat-pulldown"],
  ["Lat Pull Down (Machine)", "machine-lat-pulldown"],
  ["Lateral Raise (Cable)", "cable-lateral-raise"],
  ["Leg Press (Machine)", "leg-press"],
  ["Lunge (Barbell)", "barbell-lunge"],
  ["Lunge (Dumbbell)", "dumbbell-lunge"],
  ["Lying Leg Raise", "lying-leg-raise"],
  ["Preacher Curl (Barbell)", "barbell-preacher-curl"],
  ["Pull Up (Wide Grip)", "wide-grip-pull-up"],
  ["Reverse Fly (Cable)", "cable-reverse-fly"],
  ["Seated Overhead Press (Barbell)", "seated-barbell-press"],
  ["Seated Overhead Press (Dumbbell)", "seated-dumbbell-press"],
  ["Seated Overhead Tricep Extension (Barbell)", "seated-overhead-barbell-extension"],
  ["Shrug (Barbell)", "barbell-shrug"],
  ["Shrug (Dumbbell)", "dumbbell-shrug"],
  ["Single Leg Deadlift (Dumbbell)", "single-leg-romanian-deadlift"],
  ["Single Leg Squat", "single-leg-squat"],
  ["Tricep Dip (Bench)", "bench-dips"],
  ["Upright Row (Dumbbell)", "dumbbell-upright-row"],
  ["Bird Dog", "bird-dog"],
  ["Burpee", "burpee"],
  // GymKeeper sets noted «1рук» / «1h» / «single» / «1 нога» come as "<name> одной рукой / ногой"
  ["Seated Row (Cable) одной рукой", "one-arm-seated-row"],
  ["Incline Bench Press (Dumbbell) одной рукой", "one-arm-incline-dumbbell-press"],
  ["Standing Chest Fly (Cable) одной рукой", "single-arm-cable-crossover"],
  ["Pullover (Barbell) одной рукой", "one-arm-cable-pullover"], // noted «cbl1h»: one-arm cable pullover
  ["Hammer Strength Press (Machine) одной рукой", "one-arm-hammer-strength-press"],
  ["Lat Pull Down (Machine) одной рукой", "one-arm-machine-lat-pulldown"],
  ["Lateral Raise (Cable) одной рукой", "one-arm-cable-lateral-raise"],
  ["Leg Press (Machine) одной ногой", "single-leg-leg-press"],
  // Hevy, Russian
  ["Жим ногами (Тренажёр)", "leg-press"],
  ["Жим сидя над головой (Штанга)", "seated-barbell-press"],
  ["Наклонные сгибания на бицепс сидя (Гантель)", "incline-dumbbell-curl"],
  ["Вертикальная тяга Широчайшими (Тренажёр)", "machine-lat-pulldown"],
  ["Тяга к подбородку (Гантели)", "dumbbell-upright-row"],
  ["Вертикальная тяга (Гантель)", "dumbbell-upright-row"],
  ["Вертикальная тяга (Тренажёр)", "machine-upright-row"],
  // «Дневник тренировок» ("Жим лежа · штанга" is read as "Жим лежа (штанга)")
  ["Приседания (штанга)", "squat"],
  ["Становая тяга сумо (штанга)", "sumo-deadlift"],
  ["Румынская тяга (штанга)", "romanian-deadlift"],
  ["Ягодичный мостик (штанга)", "hip-thrust"],
  ["Ягодичный мостик", "hip-thrust"], // logged with a barbell's weights
  ["Ягодичный мостик на скамье (штанга)", "hip-thrust"],
  ["Сгибание ног (тренажер)", "leg-curl"],
  ["Сгибание ноги стоя (нижний блок)", "standing-cable-leg-curl"],
  ["Подъем на носки сидя (тренажер)", "seated-calf-raise"],
  ["Жим лежа (гантели)", "dumbbell-bench-press"],
  ["Жим лежа (наклон) (гантели)", "incline-dumbbell-press"],
  ["Жим лежа (обратный наклон) (штанга)", "decline-barbell-bench-press"],
  ["Жим от груди сидя (тренажер)", "machine-chest-press"],
  ["Сведение рук сидя (тренажер)", "machine-pec-fly"],
  ["Разведение рук лежа (гантели)", "dumbbell-fly"],
  ["Брусья на грудь", "dips"],
  ["Горизонтальная тяга сидя (блок)", "seated-row"],
  ["Вертикальная тяга прямыми руками (верхний блок)", "cable-pullover"],
  ["Подъём рук в стороны (гантели)", "lateral-raise"],
  ["Подъём рук в стороны (тренажер)", "machine-lateral-raise"],
  ["Подъем перед собой (гантели)", "dumbbell-front-raise"],
  ["Разведение рук (тренажер)", "reverse-pec-deck"],
  ["Тяга в наклоне на задние дельты (штанга)", "barbell-rear-delt-row"],
  ["Жим над головой сидя (гантели)", "seated-dumbbell-press"],
  ["Жим над головой (тренажер)", "machine-shoulder-press"],
  ["Жим над головой (тренажер Смита)", "smith-machine-shoulder-press"],
  ["Сгибание рук (штанга)", "barbell-curl"],
  ["Разгибание рук (верхний блок)", "cable-extension"],
  ["однорукий фермер", "suitcase-carry"],
  // GymKeeper, Russian export ("Жим лежа · гантели" is read as "Жим лежа (гантели)"); no equipment: by the weights logged
  ["Махи рук в стороны (гантели)", "lateral-raise"],
  ["Вертикальная тяга (верхний блок)", "lat-pulldown"],
  ["Ягодичный мостик на скамье", "hip-thrust"],
  ["Тяга на задние дельты (верхний блок)", "face-pull"],
  ["тяга на дельты", "face-pull"],
  ["Разведение ног сидя (тренажер)", "machine-hip-abduction"],
  ["Сведение ног сидя (тренажер)", "machine-hip-adduction"],
  ["Сгибание рук (гантели)", "dumbbell-curl"],
  ["Сгибание рук с супинацией (гантели)", "dumbbell-curl"],
  ["Тяга в наклоне (гантели)", "dumbbell-bent-over-row"],
  ["Пуловер (тренажер)", "machine-pullover"],
  ["Жим над головой (гантели)", "dumbbell-shoulder-press"],
  ["Румынская тяга (гантели)", "dumbbell-romanian-deadlift"],
  ["Приседания", "squat"],
  ["Жим над головой (штанга)", "overhead-press"],
  ["Приседания сумо (гантель)", "dumbbell-sumo-squat"],
  ["Вертикальная тяга узким хватом (верхний блок)", "close-grip-lat-pulldown"],
  ["Разгибание рук в наклоне (гантели)", "triceps-kickback"],
  ["Выпады (гантели)", "dumbbell-lunge"],
  ["Выпады", "dumbbell-lunge"],
  ["Разгибание рук сидя (гантель)", "seated-dumbbell-overhead-extension"],
  ["Обратные отжимания", "bench-dips"],
  ["Жим лежа узким хватом (штанга)", "close-grip-bench-press"],
  ["Сгибание рук молотковым хватом (гантели)", "hammer-curl"],
  ["Сгибание рук молотковым хватом (нижний блок)", "cable-hammer-curl"],
  ["Махи ногой назад (тренажер)", "machine-glute-kickback"],
  ["Махи ногой назад (нижний блок)", "cable-glute-kickback"],
  ["Подъем на носки стоя", "calf-raise"],
  ["Подъем на носки стоя (гантели)", "dumbbell-calf-raise"],
  ["Подъем на носок одной ноги стоя", "single-leg-calf-raise"],
  ["Жим носками (тренажер)", "leg-press-calf-raise"],
  ["Беговая дорожка", "treadmill-run"],
  ["Велосипед", "exercise-bike"],
  ["Эллипсоид", "elliptical"],
  ["Тяга в наклоне одной рукой (гантель)", "one-arm-dumbbell-row"],
  ["Тяга в наклоне одной рукой (нижний блок)", "one-arm-cable-row"],
  ["Подтягивание в гравитроне", "assisted-pull-up"],
  ["махи лёжа", "lying-rear-delt-raise"],
  ["Жим лежа (наклон) (штанга)", "incline-barbell-bench-press"],
  ["Сведение рук лежа (гантели)", "dumbbell-fly"],
  ["Сведение рук лежа (наклон) (гантели)", "incline-dumbbell-fly"],
  ["Шраги (гантели)", "dumbbell-shrug"],
  ["Шраги (тренажер Смита)", "smith-machine-shrug"],
  ["Подтягивания обратным хватом", "chin-up"],
  ["Жим от груди стоя (блок)", "standing-cable-chest-press"],
  ["Тяга верхнего блока обратным хватом", "reverse-grip-lat-pulldown"],
  ["Вертикальная тяга за голову (верхний блок)", "behind-the-neck-lat-pulldown"],
  ["Сведение согнутых рук сидя (тренажер)", "machine-pec-fly"],
  ["Сгибание рук (нижний блок)", "cable-curl"],
  ["Сгибание рук (тренажер)", "machine-curl"],
  ["Фронтальные приседания (гантель)", "dumbbell-front-squat"],
  ["Подъем ног в упоре", "captain-s-chair-leg-raise"],
  ["Подъем ног в висе", "hanging-leg-raise"],
  ["Подъемы ног лежа", "lying-leg-raise"],
  ["Приседания (тренажер Смита)", "smith-machine-squat"],
  ["Приседания (гантели)", "dumbbell-squat"],
  ["Складной нож", "v-up"],
  ["Горизонтальная рычажная тяга", "machine-row"],
  ["Планка", "plank"],
  ["Жим Арнольда (гантели)", "arnold-press"],
  ["Разгибание рук лежа (гантели)", "dumbbell-skull-crusher"],
  ["Разгибание рук лежа (штанга)", "skull-crusher"],
  ["Горизонтальные подтягивания", "inverted-row"],
  ["Тяга лежа (наклон) (гантели)", "incline-dumbbell-row"],
  ["Вышагивания на платформу (гантели)", "dumbbell-step-up"],
  ["Вышагивания на платформу", "step-up"],
  ["Становая тяга (тренажер Смита)", "smith-machine-deadlift"],
  ["Становая тяга сумо (тренажер Смита)", "smith-machine-sumo-deadlift"],
  ["Становая тяга (гантели)", "dumbbell-deadlift"],
  ["Обратные скручивания", "reverse-crunch"],
  ["Перекрестные скручивания", "cross-crunch"],
  ["Тяга в наклоне на задние дельты (гантели)", "rear-delt-row"],
  ["Прогулка фермера (гантели)", "farmer-s-walk"],
  ["Разгибание рук из-за головы (нижний блок)", "cable-extension-samurai"],
  ["Горизонтальная тяга стоя (блок)", "cable-back-row"],
  ["Тяга в наклоне (нижний блок)", "bent-over-cable-row"],
  ["Махи рук в стороны (нижний блок)", "cable-lateral-raise"],
  ["Махи рук в стороны (тренажер)", "machine-lateral-raise"],
  ["Сгибание рук на наклонной скамье (гантели)", "incline-dumbbell-curl"],
  ["Сведение рук стоя (верхний блок)", "cable-crossover"],
  ["Разгибание руки в наклоне (нижний блок)", "one-arm-cable-kickback"],
  ["Болгарские приседания (гантели)", "bulgarian-split-squat"],
  ["Болгарские приседания", "bulgarian-split-squat"],
  ["Разведение рук в наклоне (гантели)", "reverse-fly"],
  ["Гантель на дельту заднюю", "reverse-fly"],
  ["Сгибание одной руки на скамье Скотта (гантель)", "one-arm-dumbbell-preacher-curl"],
  ["Сгибания рук на скамье Скотта (штанга)", "barbell-preacher-curl"],
  ["Супермен", "superman"],
  ["Повороты корпуса (блок)", "cable-woodchop"],
  ["Ягодичный мостик (гантель)", "dumbbell-hip-thrust"],
  ["Ягодичный мостик на одной ноге", "single-leg-hip-thrust"],
  ["Выпады (штанга)", "barbell-lunge"],
  ["Доброе утро (штанга)", "good-morning"],
  ["Сгибание рук обратным хватом (гантели)", "reverse-dumbbell-curl"],
  ["Стульчик у стены", "wall-sit"],
  ["Сгибание ног лежа (гантель)", "dumbbell-lying-leg-curl"],
  ["Сплит-приседания (гантели)", "dumbbell-split-squat"],
  ["Толкание телеги", "sled-push"],
  ["Подъем перед собой (блин)", "plate-front-raise"],
  ["Скалолаз", "mountain-climber"],
];
